import { Tour, TourInstance, CANCELLATION_POLICIES } from '@/types/tours';
import { Timestamp } from 'firebase/firestore';

// ==================== TOURS MOCK DATA ====================

export const MOCK_TOURS: (Tour & { instances: TourInstance[] })[] = [
  {
    id: 'tour-astronomico-1',
    providerId: 'provider-astro-1',
    providerName: 'Astro Atacama Experiences',
    title: 'Tour Astronómico Valle de la Luna',
    description:
      'Observación de estrellas en el desierto más seco del mundo. Incluye telescopios profesionales, guía certificado y explicación del cielo austral. Perfecto para fotografía nocturna.',
    category: 'astronomico',
    images: [
      'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=600',
      'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?w=600',
    ],
    difficulty: 'facil',
    duration: 'horas',
    scheduleTag: 'noche',
    activityTypes: ['astronomia', 'fotografia', 'naturaleza'],
    basePrice: 35000,
    currency: 'CLP',
    altitude: 2400,
    groupSize: { min: 4, max: 15 },
    includes: ['Transporte', 'Telescopio', 'Guía certificado', 'Snack caliente'],
    pickupIncluded: true,
    equipmentIncluded: ['Telescopio profesional', 'Lámpara roja', 'Carta estelar'],
    physicalRequirements: 'Ninguno. Apto para todas las edades.',
    ageRestrictions: { min: 5 },
    requirements: ['Ropa abrigada', 'Calzado cómodo'],
    cancellationPolicy: CANCELLATION_POLICIES.flexible,
    rating: 4.9,
    reviewCount: 156,
    totalBookings: 420,
    status: 'active',
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    instances: [
      {
        id: 'instance-astro-1',
        tourId: 'tour-astronomico-1',
        providerId: 'provider-astro-1',
        date: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)), // En 2 días
        startTime: '21:00',
        endTime: '00:00',
        capacity: 15,
        minParticipants: 4,
        bookedSpots: 3,
        availableSpots: 12,
        pricePerPerson: 35000,
        status: 'at_risk',
        isSpecial: false,
        dynamicPricing: {
          isActive: true,
          discountPercentage: 20,
          reason: 'low_bookings',
          hoursUntilTour: 48,
          bookedPercentage: 75,
          bonusIncentives: ['Snack incluido'],
          validUntil: Timestamp.fromDate(new Date(Date.now() + 2 * 24 * 60 * 60 * 1000 - 60 * 60 * 1000)),
          createdAt: new Date(),
        },
        meetingPoint: {
          address: 'Plaza de San Pedro de Atacama',
          instructions: 'Frente a la iglesia principal',
        },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 'instance-astro-2',
        tourId: 'tour-astronomico-1',
        providerId: 'provider-astro-1',
        date: Timestamp.fromDate(new Date(Date.now() + 5 * 24 * 60 * 60 * 1000)), // En 5 días
        startTime: '21:00',
        endTime: '00:00',
        capacity: 15,
        minParticipants: 4,
        bookedSpots: 8,
        availableSpots: 7,
        pricePerPerson: 35000,
        status: 'filling',
        isSpecial: false,
        meetingPoint: {
          address: 'Plaza de San Pedro de Atacama',
          instructions: 'Frente a la iglesia principal',
        },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 'tour-geisers-tatio',
    providerId: 'provider-geisers-1',
    providerName: 'Atacama Adventure Tours',
    title: 'Géisers del Tatio al Amanecer',
    description:
      'Salida de madrugada para ver los géisers más altos del mundo en acción. Desayuno incluido con vista espectacular. Baño termal opcional.',
    category: 'geisers_tatio',
    images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600',
      'https://images.unsplash.com/photo-1483921020237-2ff51e8e4b22?w=600',
    ],
    difficulty: 'moderado',
    duration: 'medio_dia',
    scheduleTag: 'madrugada',
    activityTypes: ['naturaleza', 'aventura', 'fotografia'],
    basePrice: 45000,
    currency: 'CLP',
    altitude: 4320,
    groupSize: { min: 6, max: 20 },
    includes: ['Transporte 4x4', 'Desayuno', 'Guía', 'Entrada al parque'],
    pickupIncluded: true,
    equipmentIncluded: ['Mantas térmicas'],
    physicalRequirements: 'Resistencia a la altura. No apto para problemas cardíacos.',
    ageRestrictions: { min: 10, max: 70 },
    requirements: ['Ropa muy abrigada', 'Traje de baño (opcional)', 'Medicación para altura'],
    cancellationPolicy: CANCELLATION_POLICIES.moderate,
    rating: 4.8,
    reviewCount: 342,
    totalBookings: 890,
    status: 'active',
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    instances: [
      {
        id: 'instance-geisers-1',
        tourId: 'tour-geisers-tatio',
        providerId: 'provider-geisers-1',
        date: Timestamp.fromDate(new Date(Date.now() + 1 * 24 * 60 * 60 * 1000)), // Mañana
        startTime: '04:00',
        endTime: '12:00',
        capacity: 20,
        minParticipants: 6,
        bookedSpots: 18,
        availableSpots: 2,
        pricePerPerson: 45000,
        status: 'almost_full',
        isSpecial: false,
        meetingPoint: {
          address: 'Calle Toconao 420, San Pedro de Atacama',
          instructions: 'Oficina de Atacama Adventure Tours',
        },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 'tour-valle-luna',
    providerId: 'provider-valle-1',
    providerName: 'Desert Explorers',
    title: 'Valle de la Luna al Atardecer',
    description:
      'Explora paisajes marcianos y observa el atardecer más espectacular del desierto. Incluye Duna Mayor y Caverna de Sal.',
    category: 'valle_luna_muerte',
    images: [
      'https://images.unsplash.com/photo-1682687220742-aba13b6e50ba?w=600',
      'https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=600',
    ],
    difficulty: 'facil',
    duration: 'medio_dia',
    scheduleTag: 'atardecer',
    activityTypes: ['fotografia', 'naturaleza', 'cultural'],
    basePrice: 25000,
    currency: 'CLP',
    altitude: 2500,
    groupSize: { min: 4, max: 12 },
    includes: ['Transporte', 'Guía', 'Entrada al parque', 'Snack'],
    pickupIncluded: true,
    equipmentIncluded: [],
    physicalRequirements: 'Caminar por terreno irregular.',
    ageRestrictions: { min: 6 },
    requirements: ['Protector solar', 'Sombrero', 'Agua'],
    cancellationPolicy: CANCELLATION_POLICIES.flexible,
    rating: 4.7,
    reviewCount: 234,
    totalBookings: 678,
    status: 'active',
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    instances: [
      {
        id: 'instance-valle-1',
        tourId: 'tour-valle-luna',
        providerId: 'provider-valle-1',
        date: Timestamp.fromDate(new Date(Date.now() + 3 * 24 * 60 * 60 * 1000)), // En 3 días
        startTime: '16:00',
        endTime: '20:00',
        capacity: 12,
        minParticipants: 4,
        bookedSpots: 5,
        availableSpots: 7,
        pricePerPerson: 25000,
        status: 'confirmed',
        isSpecial: false,
        meetingPoint: {
          address: 'Plaza de San Pedro de Atacama',
        },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 'tour-lagunas-altiplanicas',
    providerId: 'provider-lagunas-1',
    providerName: 'Highland Adventures',
    title: 'Lagunas Altiplánicas & Salar de Atacama',
    description:
      'Tour de día completo visitando las lagunas Miscanti y Miñiques, Salar de Atacama y Laguna Chaxa. Almuerzo incluido.',
    category: 'lagunas_altiplanicas',
    images: [
      'https://images.unsplash.com/photo-1682687982501-1e58ab814714?w=600',
      'https://images.unsplash.com/photo-1682687982029-1597dfc90eda?w=600',
    ],
    difficulty: 'moderado',
    duration: 'dia_completo',
    scheduleTag: 'manana',
    activityTypes: ['naturaleza', 'fotografia', 'cultural'],
    basePrice: 55000,
    currency: 'CLP',
    altitude: 4200,
    groupSize: { min: 6, max: 16 },
    includes: ['Transporte 4x4', 'Almuerzo', 'Guía bilingüe', 'Entradas'],
    pickupIncluded: true,
    equipmentIncluded: ['Binoculares para observación de aves'],
    physicalRequirements: 'Resistencia moderada a la altura.',
    ageRestrictions: { min: 8, max: 75 },
    requirements: ['Ropa abrigada', 'Protector solar', 'Gafas de sol', 'Medicación para altura'],
    cancellationPolicy: CANCELLATION_POLICIES.moderate,
    rating: 4.9,
    reviewCount: 198,
    totalBookings: 534,
    status: 'active',
    featured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    instances: [
      {
        id: 'instance-lagunas-1',
        tourId: 'tour-lagunas-altiplanicas',
        providerId: 'provider-lagunas-1',
        date: Timestamp.fromDate(new Date(Date.now() + 4 * 24 * 60 * 60 * 1000)), // En 4 días
        startTime: '08:00',
        endTime: '18:00',
        capacity: 16,
        minParticipants: 6,
        bookedSpots: 10,
        availableSpots: 6,
        pricePerPerson: 55000,
        status: 'confirmed',
        isSpecial: false,
        meetingPoint: {
          address: 'Caracoles 166, San Pedro de Atacama',
          instructions: 'Oficina Highland Adventures',
        },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
  {
    id: 'tour-sandboarding',
    providerId: 'provider-extreme-1',
    providerName: 'Extreme Atacama',
    title: 'Sandboarding Valle de la Muerte',
    description:
      'Adrenalina pura deslizándote por las dunas del Valle de la Muerte. Para todos los niveles. Equipo profesional incluido.',
    category: 'sandboarding',
    images: [
      'https://images.unsplash.com/photo-1527004013197-933c4bb611b3?w=600',
      'https://images.unsplash.com/photo-1682687220945-922d0f38d3b1?w=600',
    ],
    difficulty: 'moderado',
    duration: 'medio_dia',
    scheduleTag: 'tarde',
    activityTypes: ['aventura', 'deportes'],
    basePrice: 30000,
    currency: 'CLP',
    altitude: 2450,
    groupSize: { min: 3, max: 10 },
    includes: ['Transporte', 'Tabla de sandboarding', 'Instructor', 'Seguro de accidentes'],
    pickupIncluded: true,
    equipmentIncluded: ['Tabla profesional', 'Casco', 'Rodilleras', 'Guantes'],
    physicalRequirements: 'Buena condición física. Experiencia en deportes de deslizamiento recomendada.',
    ageRestrictions: { min: 12, max: 60 },
    requirements: ['Ropa deportiva', 'Calzado cerrado', 'Protector solar'],
    cancellationPolicy: CANCELLATION_POLICIES.flexible,
    rating: 4.6,
    reviewCount: 87,
    totalBookings: 234,
    status: 'active',
    featured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    instances: [
      {
        id: 'instance-sandboarding-1',
        tourId: 'tour-sandboarding',
        providerId: 'provider-extreme-1',
        date: Timestamp.fromDate(new Date(Date.now() + 6 * 24 * 60 * 60 * 1000)), // En 6 días
        startTime: '15:00',
        endTime: '18:00',
        capacity: 10,
        minParticipants: 3,
        bookedSpots: 2,
        availableSpots: 8,
        pricePerPerson: 24000, // Con descuento
        originalPrice: 30000,
        status: 'at_risk',
        isSpecial: false,
        dynamicPricing: {
          isActive: true,
          discountPercentage: 20,
          reason: 'low_bookings',
          hoursUntilTour: 144,
          bookedPercentage: 67,
          bonusIncentives: ['GoPro para fotos gratis'],
          validUntil: Timestamp.fromDate(new Date(Date.now() + 6 * 24 * 60 * 60 * 1000 - 60 * 60 * 1000)),
          createdAt: new Date(),
        },
        meetingPoint: {
          address: 'Tocopilla 411, San Pedro de Atacama',
        },
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
  },
];
